
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-customer-depl
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-customer
  template:
    metadata:
      labels:
        app: pitstop-customer
    spec:
      containers:
        - name: pitstop-customer
          image: devops4project/customer-service:5e52d9b
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: pitstop-customer-configmap
