
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-webapp-deployment
  namespace: pitstop
  labels:
    app: pitstop-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-webapp
  template:
    metadata:
      labels:
        app: pitstop-webapp
    spec:
      containers:
        - name: pitstop-webapp
          image: devops4project/pitstop-webapp:a1544f3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pitstop-webapp-configmap
