apiVersion : argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project : default
  source:
    repoURL: https://github.com/zakachaara/product-microservice-k8s.git
    targetRevision: HEAD
    path: pitstop

  destination:
    server: https://kubernetes.default.svc
    namespace: pitstop
  
  syncPolicy:
    syncOptions:
    - CreateNamespace =true
    automated :
      selfHeal: true
      prune: true