apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-gateway-configmap
  namespace: pitstop
data:
    PORT: "8080"
    CUSTOMER_URL: "pitstop-customer-service:3001"
    VEHICLE_URL: "pitstop-vehicle-service:3002"
    WORKSHOP_URL: "pitstop-workshop-service:3003"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-gateway-depl
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-gateway
  template:
    metadata:
      labels:
        app: pitstop-gateway
    spec:
      containers:
        - name: pitstop-gateway
          image: msalekmouad/pitstop-express-gateway:dev
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pitstop-gateway-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-gateway-service
  namespace: pitstop
spec:
  ports:
    - port: 8080
  type: NodePort
  selector:
    app: pitstop-gateway
