apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-customer-configmap
  namespace: pitstop
data:
    DB_USER: pitstop-user
    DB_PASSWORD: pitstop-user
    DB_NAME: pitstop
    DB_HOST: pitstop-customer-database-service
    DB_PORT: "3307"
    SERVICE_NAME: pitstop-customer
    PORT: "3001"
    MESSAGE_BUS: pitstop-rabbitmq-service
    MESSAGE_BUS_USERNAME: pitstop
    MESSAGE_BUS_PASSWORD: pitstop
    MESSAGE_BUS_TIMEOUT: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-customer-service
  namespace: pitstop
spec:
  ports:
    - port: 3001
  type: NodePort
  selector:
    app: pitstop-customer
