
apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-webapp-configmap
  namespace: pitstop
data:
  VUE_APP_API_BASE_URL: "http://pitstop-gateway-service:8080" # Example environment variable for API base URL

---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-webapp-service
  namespace: pitstop
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort
  selector:
    app: pitstop-webapp
